///////////////////////////////////////////////////////////////////////////////////////
// Data Analysis Code Project for the External Target Facility, HIRFL-CSR, @IMP      //
//																				     //
// etf/inc/VMEAnalyze.C																 //
//   read.C -- definition for function void analyze(int *data, tVME_event &event)	 //
//   Introduction: reading one event recorded in data block generated by VME 		 //
// electronics.																		 //
//																				     //
// Author: SUN Yazhou, asia.rabbit@163.com.										     //
// Created: 2016/11/15, transported: 2018/1/9.									     //
// Last modified: 2018/1/27, SUN Yazhou.											 //
//																				     //
//																				     //
// Copyright (C) 2017-2018, SUN Yazhou.											     //
// All rights reserved.															     //
///////////////////////////////////////////////////////////////////////////////////////

void TABUAA::analyze(const int *data, tVME_event &ev){
//	cout << "Getting into analyze(...)." << endl; // DEBUG
	double length = ev.length;
//	cout << "length: " << length << endl; // DEBUG
//	getchar(); // DEBUG

	int chData; // each int in data. A temporary variable.
	int slot, header, geo, chid, nums;
//	int cnt = 0; // DEBUG
	int id_v1290 = 0, id_v830 = 0, v830_shutdown = 0;
	int pos = 0; // subscipt of array data.

	for(int i = 0; i < length; i++){ // loop over channels
//		cout << "pos: " << pos << endl; // DEBUG
		chData = data[pos];
		geo = chData & 0x1F;
		slot = (chData >> 27) & 0x1F;
		header = (chData >> 24) & 0x7;
//		cout << "chData: " << chData << endl; // DEBUG
//		cout << "geo: " << geo << endl; // DEBUG
//		cout << "slot: " << slot << endl; // DEBUG
//		cout << "header: " << header << endl; // DEBUG
//		getchar(); // DEBUG
		
		if(header == 0 && (slot==3||slot==4||slot==6||slot==7||slot==9||slot==11)){
			chid = (chData >> 16) & 0x1F;
//			cout << "chid: " << chid << endl; // DEBUG
//			getchar(); // DEBUG
			switch(slot){
				case 4: ev.adc[chid] = chData & 0xFFF;
//					cout << "ev.adc[chid]: " << ev.adc[chid] << endl; // DEBUG
//					getchar(); // DEBUG
					break; // adc
				case 3: ev.qdc[0][chid] = chData & 0xFFF;
//					cout << "ev.qdc[0][chid]: " << ev.qdc[0][chid] << endl; // DEBUG
//					getchar(); // DEBUG
					break; // qdc0
				case 6: ev.qdc[1][chid] = chData & 0xFFF;
//					cout << "ev.qdc[1][chid]: " << ev.qdc[1][chid] << endl; // DEBUG
//					getchar(); // DEBUG
					break; // qdc1
				case 7: ev.qdc[2][chid] = chData & 0xFFF;
//					cout << "ev.qdc[2][chid]: " << ev.qdc[2][chid] << endl; // DEBUG
//					getchar(); // DEBUG
					break; // qdc2
				case 9: ev.tdc[0][chid] = chData & 0xFFF;
//					cout << "ev.tdc[0][chid]: " << ev.tdc[0][chid] << endl; // DEBUG
//					getchar(); // DEBUG
					break; // tdc0
				case 11: ev.tdc[1][chid] = chData & 0xFFF;
//					cout << "ev.tdc[1][chid]: " << ev.tdc[1][chid] << endl; // DEBUG
//					getchar(); // DEBUG
					break; // tdc1
				default: break;
			} // end switch
		} // end if
		else if(header==2 && (slot==3||slot==4||slot==6||slot==7||slot==9||slot==11)){
//			if(header == 2) cnt = (chData >> 8) & 0x3F; // DEBUG
//			cout << "cnt: " << cnt << endl; // DEBUG
//			getchar(); // DEBUG
		} // end if
		else if(header==4 && (slot==3||slot==4||slot==6||slot==7||slot==9||slot==11)){}
		else if(slot == 8 && geo == 13){
			id_v1290 = 1;
			for(int j = 0; j < 32; j++) ev.hit[j] = 0;
		} // end if
		else if(slot == 1 && id_v1290 == 1){}
		else if(slot == 0 && id_v1290 == 1){
			chid = (chData >> 21) & 0x1F;
			ev.mtdc[chid][ev.hit[chid]++] = chData & 0xFFFFF;
//			cout << "chid: " << chid << endl; // DEBUG
//			cout << "ev.hit[chid]: " << ev.hit[chid] << endl; // DEBUG
//			cout << "ev.mtdc[chid][ev.hit[chid]]: " << ev.mtdc[chid][ev.hit[chid]] << endl; // DEBUG
//			getchar(); // DEBUG
		} // end if
		else if(slot == 3 && id_v1290 == 1){
//			cnt = chData & 0xFFF; // DEBUG
//			cout << "id_v1290, cnt: " << cnt << endl; // DEBUG
//			getchar(); // DEBUG
		} // end if
		else if(slot == 16 && geo == 13){
			id_v1290 = 0;
		} // end if
		else if(slot == 19 && geo == 16){
//			cout << "v830 header" << endl; // DEBUG
//			getchar(); // DEBUG
			id_v830 = 1;
			nums = 0;
		} // end if
		// v830_shutdown: added by WANG Shitao,
		// so that sca would be read only once for each trigger.
		else if(id_v830 == 1 && v830_shutdown == 0){ // id_v830 == 1 and v830_shutdown == 0
			ev.psca[nums] = ev.sca[nums];
			ev.sca[nums] = chData & 0xFFFFFFFF;
			ev.dsca[nums] = ev.sca[nums] - ev.psca[nums];
			nums++;
//			cout << "nums: " << nums << endl; // DEBUG
//			cout << "ev.psca[nums]: " << ev.psca[nums] << endl; // DEBUG
//			cout << "ev.sca[nums]: " << ev.sca[nums] << endl; // DEBUG
//			cout << "ev.dsca[nums]: " << ev.dsca[nums] << endl; // DEBUG
//			getchar(); // DEBUG
			if(nums == 16){
				id_v830 = 0;
				v830_shutdown = 1;
			} // end if(nums == 16)
		} // end if
		pos++; // point to next ints in array data.
	} // end for over i
} // end of function analyze(int *, tVME_event &).

