//
// File generated by C:\root\/bin/rootcint at Wed Nov 17 23:04:29 2010

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "OnFdict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void OnlineFrame_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_OnlineFrame(void *p);
   static void deleteArray_OnlineFrame(void *p);
   static void destruct_OnlineFrame(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::OnlineFrame*)
   {
      ::OnlineFrame *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::OnlineFrame >(0);
      static ::ROOT::TGenericClassInfo 
         instance("OnlineFrame", ::OnlineFrame::Class_Version(), "E:/DAQ_8B2010/W_online//W_online/OnlineFrame.h", 35,
                  typeid(::OnlineFrame), DefineBehavior(ptr, ptr),
                  &::OnlineFrame::Dictionary, isa_proxy, 0,
                  sizeof(::OnlineFrame) );
      instance.SetDelete(&delete_OnlineFrame);
      instance.SetDeleteArray(&deleteArray_OnlineFrame);
      instance.SetDestructor(&destruct_OnlineFrame);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::OnlineFrame*)
   {
      return GenerateInitInstanceLocal((::OnlineFrame*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::OnlineFrame*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *OnlineFrame::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *OnlineFrame::Class_Name()
{
   return "OnlineFrame";
}

//______________________________________________________________________________
const char *OnlineFrame::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::OnlineFrame*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int OnlineFrame::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::OnlineFrame*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void OnlineFrame::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::OnlineFrame*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *OnlineFrame::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::OnlineFrame*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void OnlineFrame::Streamer(TBuffer &R__b)
{
   // Stream an object of class OnlineFrame.

   TGMainFrame::Streamer(R__b);
}

//______________________________________________________________________________
void OnlineFrame::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class OnlineFrame.
      typedef ::OnlineFrame msvc_bug_workaround;
      TClass *R__cl = msvc_bug_workaround::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fFFileList", &fFFileList);
      R__insp.Inspect(R__cl, R__parent, "*fFButton", &fFButton);
      R__insp.Inspect(R__cl, R__parent, "*fFTextView", &fFTextView);
      R__insp.Inspect(R__cl, R__parent, "*flabDrawOpt", &flabDrawOpt);
      R__insp.Inspect(R__cl, R__parent, "*flabText", &flabText);
      R__insp.Inspect(R__cl, R__parent, "*fcomDrawOpt", &fcomDrawOpt);
      R__insp.Inspect(R__cl, R__parent, "*flvFile", &flvFile);
      R__insp.Inspect(R__cl, R__parent, "*fFileCont", &fFileCont);
      R__insp.Inspect(R__cl, R__parent, "*fBonline", &fBonline);
      R__insp.Inspect(R__cl, R__parent, "*fBoffline", &fBoffline);
      R__insp.Inspect(R__cl, R__parent, "*fBresetcurr", &fBresetcurr);
      R__insp.Inspect(R__cl, R__parent, "*fBresetall", &fBresetall);
      R__insp.Inspect(R__cl, R__parent, "*fBprevious", &fBprevious);
      R__insp.Inspect(R__cl, R__parent, "*fBnext", &fBnext);
      R__insp.Inspect(R__cl, R__parent, "*fBupdate", &fBupdate);
      R__insp.Inspect(R__cl, R__parent, "*fBintegral", &fBintegral);
      R__insp.Inspect(R__cl, R__parent, "*fBexit", &fBexit);
      R__insp.Inspect(R__cl, R__parent, "*fviewText", &fviewText);
      TGMainFrame::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_OnlineFrame(void *p) {
      delete ((::OnlineFrame*)p);
   }
   static void deleteArray_OnlineFrame(void *p) {
      delete [] ((::OnlineFrame*)p);
   }
   static void destruct_OnlineFrame(void *p) {
      typedef ::OnlineFrame current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::OnlineFrame

/********************************************************
* E:\DAQ_8B2010\W_online\\W_online\OnFdict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtableOnFdict();

extern "C" void G__set_cpp_environmentOnFdict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("E:\\DAQ_8B2010\\W_online\\\\W_online\\OnlineFrame.h");
  G__cpp_reset_tagtableOnFdict();
}
#include <new>
extern "C" int G__cpp_dllrevOnFdict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* OnlineFrame */
static int G__OnFdict_442_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   OnlineFrame* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new OnlineFrame(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) OnlineFrame(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__OnFdictLN_OnlineFrame));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__OnFdict_442_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) OnlineFrame::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__OnFdict_442_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) OnlineFrame::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__OnFdict_442_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) OnlineFrame::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__OnFdict_442_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      OnlineFrame::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__OnFdict_442_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((OnlineFrame*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__OnFdict_442_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) OnlineFrame::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__OnFdict_442_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) OnlineFrame::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__OnFdict_442_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) OnlineFrame::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__OnFdict_442_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) OnlineFrame::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef OnlineFrame G__TOnlineFrame;
static int G__OnFdict_442_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (OnlineFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((OnlineFrame*) (soff+(sizeof(OnlineFrame)*i)))->~G__TOnlineFrame();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (OnlineFrame*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((OnlineFrame*) (soff))->~G__TOnlineFrame();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* OnlineFrame */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncOnFdict {
 public:
  G__Sizep2memfuncOnFdict(): p(&G__Sizep2memfuncOnFdict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncOnFdict::*p)();
};

size_t G__get_sizep2memfuncOnFdict()
{
  G__Sizep2memfuncOnFdict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceOnFdict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__OnFdictLN_OnlineFrame))) {
     OnlineFrame *G__Lderived;
     G__Lderived=(OnlineFrame*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__OnFdictLN_OnlineFrame),G__get_linked_tagnum(&G__OnFdictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__OnFdictLN_OnlineFrame),G__get_linked_tagnum(&G__OnFdictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__OnFdictLN_OnlineFrame),G__get_linked_tagnum(&G__OnFdictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__OnFdictLN_OnlineFrame),G__get_linked_tagnum(&G__OnFdictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__OnFdictLN_OnlineFrame),G__get_linked_tagnum(&G__OnFdictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__OnFdictLN_OnlineFrame),G__get_linked_tagnum(&G__OnFdictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__OnFdictLN_OnlineFrame),G__get_linked_tagnum(&G__OnFdictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableOnFdict() {

   /* Setting up typedef entry */
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__OnFdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("_Ranit<ROOT::TSchemaHelper,difference_type,const_pointer,const_reference>",117,G__get_linked_tagnum(&G__OnFdictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,G__get_linked_tagnum(&G__OnFdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__OnFdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__OnFdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__OnFdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>::reference>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__OnFdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__OnFdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::iterator_category,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::value_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::difference_type,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::pointer,iterator_traits<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__OnFdictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("_Ranit<TStreamerInfo*,difference_type,const_pointer,const_reference>",117,G__get_linked_tagnum(&G__OnFdictLN__RanitlETStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR),0,G__get_linked_tagnum(&G__OnFdictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TStreamerInfo*>",117,G__get_linked_tagnum(&G__OnFdictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__OnFdictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__OnFdictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>::iterator_category,iterator_traits<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>::value_type,iterator_traits<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>::difference_type,iterator_traits<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>::pointer,iterator_traits<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>::reference>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TStreamerInfo*>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TStreamerInfo*,long>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TStreamerInfo*,long,TStreamerInfo**>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__OnFdictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__OnFdictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::const_iterator>::iterator_category,iterator_traits<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::const_iterator>::value_type,iterator_traits<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::const_iterator>::difference_type,iterator_traits<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::const_iterator>::pointer,iterator_traits<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__OnFdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("_Ranit<TVirtualArray*,difference_type,const_pointer,const_reference>",117,G__get_linked_tagnum(&G__OnFdictLN__RanitlETVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,G__get_linked_tagnum(&G__OnFdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__OnFdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__OnFdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__OnFdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>::reference>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__OnFdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR),0,G__get_linked_tagnum(&G__OnFdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::iterator_category,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::value_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::difference_type,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::pointer,iterator_traits<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>::reference>",117,G__get_linked_tagnum(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* OnlineFrame */
static void G__setup_memvarOnlineFrame(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__OnFdictLN_OnlineFrame));
   { OnlineFrame *p; p=(OnlineFrame*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGVerticalFrame),-1,-1,2,"fFFileList=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGHorizontalFrame),-1,-1,2,"fFButton=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGHorizontalFrame),-1,-1,2,"fFTextView=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGLabel),-1,-1,2,"flabDrawOpt=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGLabel),-1,-1,2,"flabText=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGComboBox),-1,-1,2,"fcomDrawOpt=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGListView),-1,-1,2,"flvFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGFileContainer),-1,-1,2,"fFileCont=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGTextButton),-1,-1,2,"fBonline=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGTextButton),-1,-1,2,"fBoffline=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGTextButton),-1,-1,2,"fBresetcurr=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGTextButton),-1,-1,2,"fBresetall=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGTextButton),-1,-1,2,"fBprevious=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGTextButton),-1,-1,2,"fBnext=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGTextButton),-1,-1,2,"fBupdate=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGTextButton),-1,-1,2,"fBintegral=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGTextButton),-1,-1,2,"fBexit=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TGTextView),-1,-1,2,"fviewText=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__OnFdictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarOnFdict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncOnlineFrame(void) {
   /* OnlineFrame */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__OnFdictLN_OnlineFrame));
   G__memfunc_setup("OnlineFrame",1104,G__OnFdict_442_0_1, 105, G__get_linked_tagnum(&G__OnFdictLN_OnlineFrame), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CloseWindow",1134,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("OnlineFrame",1104,(G__InterfaceMethod) NULL, 105, G__get_linked_tagnum(&G__OnFdictLN_OnlineFrame), -1, 0, 1, 1, 2, 0, "u 'OnlineFrame' - 11 - onf", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator=",937,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__OnFdictLN_OnlineFrame), -1, 1, 1, 1, 2, 0, "u 'OnlineFrame' - 11 - onf", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__OnFdict_442_0_5, 85, G__get_linked_tagnum(&G__OnFdictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&OnlineFrame::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__OnFdict_442_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&OnlineFrame::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__OnFdict_442_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&OnlineFrame::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__OnFdict_442_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&OnlineFrame::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__OnFdictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__OnFdict_442_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__OnFdict_442_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&OnlineFrame::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__OnFdict_442_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&OnlineFrame::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__OnFdict_442_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&OnlineFrame::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__OnFdict_442_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&OnlineFrame::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~OnlineFrame", 1230, G__OnFdict_442_0_17, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncOnFdict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalOnFdict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcOnFdict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__OnFdictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__OnFdictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR = { "_Ranit<ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*,ROOT::TSchemaHelper&>" , 115 , -1 };
G__linked_taginfo G__OnFdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR = { "iterator<random_access_iterator_tag,ROOT::TSchemaHelper,long,ROOT::TSchemaHelper*,ROOT::TSchemaHelper&>" , 115 , -1 };
G__linked_taginfo G__OnFdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__OnFdictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_TGVerticalFrame = { "TGVerticalFrame" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_TGHorizontalFrame = { "TGHorizontalFrame" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_TGLabel = { "TGLabel" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_TGListView = { "TGListView" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_TGComboBox = { "TGComboBox" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR = { "vector<TStreamerInfo*,allocator<TStreamerInfo*> >" , 99 , -1 };
G__linked_taginfo G__OnFdictLN__RanitlETStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR = { "_Ranit<TStreamerInfo*,long,TStreamerInfo**,TStreamerInfo*&>" , 115 , -1 };
G__linked_taginfo G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR = { "iterator<random_access_iterator_tag,TStreamerInfo*,long,TStreamerInfo**,TStreamerInfo*&>" , 115 , -1 };
G__linked_taginfo G__OnFdictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<TStreamerInfo*,allocator<TStreamerInfo*> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__OnFdictLN__RanitlETVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR = { "_Ranit<TVirtualArray*,long,TVirtualArray**,TVirtualArray*&>" , 115 , -1 };
G__linked_taginfo G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR = { "iterator<random_access_iterator_tag,TVirtualArray*,long,TVirtualArray**,TVirtualArray*&>" , 115 , -1 };
G__linked_taginfo G__OnFdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::const_iterator>" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_TGFileContainer = { "TGFileContainer" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_TGTextView = { "TGTextView" , 99 , -1 };
G__linked_taginfo G__OnFdictLN_OnlineFrame = { "OnlineFrame" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableOnFdict() {
  G__OnFdictLN_TClass.tagnum = -1 ;
  G__OnFdictLN_TBuffer.tagnum = -1 ;
  G__OnFdictLN_TMemberInspector.tagnum = -1 ;
  G__OnFdictLN_TObject.tagnum = -1 ;
  G__OnFdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__OnFdictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR.tagnum = -1 ;
  G__OnFdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR.tagnum = -1 ;
  G__OnFdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__OnFdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__OnFdictLN_TGObject.tagnum = -1 ;
  G__OnFdictLN_TQObject.tagnum = -1 ;
  G__OnFdictLN_TGWindow.tagnum = -1 ;
  G__OnFdictLN_TGFrame.tagnum = -1 ;
  G__OnFdictLN_TGCompositeFrame.tagnum = -1 ;
  G__OnFdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__OnFdictLN_TGTextButton.tagnum = -1 ;
  G__OnFdictLN_TGVerticalFrame.tagnum = -1 ;
  G__OnFdictLN_TGHorizontalFrame.tagnum = -1 ;
  G__OnFdictLN_TGMainFrame.tagnum = -1 ;
  G__OnFdictLN_TGLabel.tagnum = -1 ;
  G__OnFdictLN_TGListView.tagnum = -1 ;
  G__OnFdictLN_TGComboBox.tagnum = -1 ;
  G__OnFdictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR.tagnum = -1 ;
  G__OnFdictLN__RanitlETStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR.tagnum = -1 ;
  G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR.tagnum = -1 ;
  G__OnFdictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__OnFdictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__OnFdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__OnFdictLN__RanitlETVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR.tagnum = -1 ;
  G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR.tagnum = -1 ;
  G__OnFdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__OnFdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR.tagnum = -1 ;
  G__OnFdictLN_TGFileContainer.tagnum = -1 ;
  G__OnFdictLN_TGTextView.tagnum = -1 ;
  G__OnFdictLN_OnlineFrame.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableOnFdict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TClass);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TObject);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__OnFdictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TGVerticalFrame);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TGHorizontalFrame);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TGLabel);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TGListView);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TGComboBox);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR);
   G__get_linked_tagnum_fwd(&G__OnFdictLN__RanitlETStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__OnFdictLN__RanitlETVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TGFileContainer);
   G__get_linked_tagnum_fwd(&G__OnFdictLN_TGTextView);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__OnFdictLN_OnlineFrame),sizeof(OnlineFrame),-1,65024,(char*)NULL,G__setup_memvarOnlineFrame,G__setup_memfuncOnlineFrame);
}
extern "C" void G__cpp_setupOnFdict(void) {
  G__check_setup_version(30051515,"G__cpp_setupOnFdict()");
  G__set_cpp_environmentOnFdict();
  G__cpp_setup_tagtableOnFdict();

  G__cpp_setup_inheritanceOnFdict();

  G__cpp_setup_typetableOnFdict();

  G__cpp_setup_memvarOnFdict();

  G__cpp_setup_memfuncOnFdict();
  G__cpp_setup_globalOnFdict();
  G__cpp_setup_funcOnFdict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncOnFdict();
  return;
}
class G__cpp_setup_initOnFdict {
  public:
    G__cpp_setup_initOnFdict() { G__add_setup_func("OnFdict",(G__incsetup)(&G__cpp_setupOnFdict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initOnFdict() { G__remove_setup_func("OnFdict"); }
};
G__cpp_setup_initOnFdict G__cpp_setup_initializerOnFdict;

