/********************************************************************
* E:\DAQ_8B2010\W_online\\W_online\OnFdict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error E:\DAQ_8B2010\W_online\\W_online\OnFdict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern G__DLLEXPORT int G__cpp_dllrevOnFdict();
extern G__DLLEXPORT void G__set_cpp_environmentOnFdict();
extern G__DLLEXPORT void G__cpp_setup_tagtableOnFdict();
extern G__DLLEXPORT void G__cpp_setup_inheritanceOnFdict();
extern G__DLLEXPORT void G__cpp_setup_typetableOnFdict();
extern G__DLLEXPORT void G__cpp_setup_memvarOnFdict();
extern G__DLLEXPORT void G__cpp_setup_globalOnFdict();
extern G__DLLEXPORT void G__cpp_setup_memfuncOnFdict();
extern G__DLLEXPORT void G__cpp_setup_funcOnFdict();
extern G__DLLEXPORT void G__cpp_setupOnFdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "E:\\DAQ_8B2010\\W_online\\\\W_online\\OnlineFrame.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__OnFdictLN_TClass;
extern G__linked_taginfo G__OnFdictLN_TBuffer;
extern G__linked_taginfo G__OnFdictLN_TMemberInspector;
extern G__linked_taginfo G__OnFdictLN_TObject;
extern G__linked_taginfo G__OnFdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__OnFdictLN__RanitlEROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__OnFdictLN_iteratorlErandom_access_iterator_tagcOROOTcLcLTSchemaHelpercOlongcOROOTcLcLTSchemaHelpermUcOROOTcLcLTSchemaHelperaNgR;
extern G__linked_taginfo G__OnFdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__OnFdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__OnFdictLN_TGObject;
extern G__linked_taginfo G__OnFdictLN_TQObject;
extern G__linked_taginfo G__OnFdictLN_TGWindow;
extern G__linked_taginfo G__OnFdictLN_TGFrame;
extern G__linked_taginfo G__OnFdictLN_TGCompositeFrame;
extern G__linked_taginfo G__OnFdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__OnFdictLN_TGTextButton;
extern G__linked_taginfo G__OnFdictLN_TGVerticalFrame;
extern G__linked_taginfo G__OnFdictLN_TGHorizontalFrame;
extern G__linked_taginfo G__OnFdictLN_TGMainFrame;
extern G__linked_taginfo G__OnFdictLN_TGLabel;
extern G__linked_taginfo G__OnFdictLN_TGListView;
extern G__linked_taginfo G__OnFdictLN_TGComboBox;
extern G__linked_taginfo G__OnFdictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__OnFdictLN__RanitlETStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR;
extern G__linked_taginfo G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTStreamerInfomUcOlongcOTStreamerInfomUmUcOTStreamerInfomUaNgR;
extern G__linked_taginfo G__OnFdictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__OnFdictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__OnFdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__OnFdictLN__RanitlETVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__OnFdictLN_iteratorlErandom_access_iterator_tagcOTVirtualArraymUcOlongcOTVirtualArraymUmUcOTVirtualArraymUaNgR;
extern G__linked_taginfo G__OnFdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__OnFdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLconst_iteratorgR;
extern G__linked_taginfo G__OnFdictLN_TGFileContainer;
extern G__linked_taginfo G__OnFdictLN_TGTextView;
extern G__linked_taginfo G__OnFdictLN_OnlineFrame;

/* STUB derived class for protected member access */
